
Когда в нашей программе происходит какая-то ошибка, она прерывает своё выполнение и в консоль идет сообщение об типе ошибки (возникшем исключении)

Исключения (exceptions) - ещё один тип данных в python. Исключения необходимы для того, чтобы сообщать программисту об ошибках.

Самый простейший пример исключения - деление на ноль:

```

>>> 100 / 0
Traceback (most recent call last):
  File "", line 1, in
    100 / 0
ZeroDivisionError: division by zero

```

Разберём это сообщение подробнее: интерпретатор нам сообщает о том, что он поймал исключение и напечатал информацию (**Traceback (most recent call last)**).

Далее имя файла (**File ""**). Имя пустое, потому что мы находимся в интерактивном режиме, строка в файле (**line 1**);

Выражение, в котором произошла ошибка (**100 / 0**).

Название исключения (**ZeroDivisionError**) и краткое описание исключения (**division by zero**).

Разумеется, возможны и другие исключения.

# ЧТО ДЕЛАТЬ С ИСКЛЮЧЕНИЯМИ?

Так как мы не всегда хотим, чтобы наш код прерывался из-за возникшего исключения, нам надо сделать так, чтобы Python мог "попробовать" выполнить участок кода, если все нормально и он спокойно выполняется, просто программа идет дальше, если нет и у нас в какой-то строке возникает ошибка, то он должен выполнить какую-то логику (обработать исключение) и продолжить выполнять код дальше.

Для обработки исключений используется конструкция **try - except**.

Первый пример применения этой конструкции:

```python

>>> try:
...     k = 1 / 0
... except ZeroDivisionError:
...     k = 0
...
>>> print(k)
0

```

В блоке try мы выполняем инструкцию, которая может породить исключение, а в блоке except мы перехватываем их. При этом перехватываются как само исключение, так и его потомки. Например, перехватывая ArithmeticError, мы также перехватываем FloatingPointError, OverflowError и ZeroDivisionError.

```python

>>> try:
...     k = 1 / 0
... except ArithmeticError:
...     k = 0
...
>>> print(k)
0

```

Также возможна инструкция except без аргументов, которая перехватывает вообще всё (и прерывание с клавиатуры, и системный выход и т. д.). Поэтому в такой форме инструкция except практически не используется, а используется except Exception. Однако чаще всего перехватывают исключения по одному, для упрощения отладки (вдруг вы ещё другую ошибку сделаете, а except её перехватит).

---

# ПОЛНЫЙ СИНТАКСИС TRY EXCEPT ELSE FINALY

Полный синтаксис конструкции try в Python выглядит следующим образом:


```python

try:
       # Код, который потенциально может привести к ошибке
except SomeError:
       # Опциональный блок, перехватывает ошибку SomeError, 
       # если она возникает, выполняется опеределенная логика
except:
       # Опциональный блок, перехватывает любую ошибку, 
       # если она возникает, выполняется опеределенная логика
else:
       # опциональный блок: выполняется если исключений не возникло
finally:
      # Код, выполняется в любом случае в конце после try + else или except

```

> [!Резюмируем:]
> - Обязателен только try
> - Except выполниться только при возникновении ошибки
> - else выполняет только если try отработал без исключений, то есть при работе кода без ошибки выполняется try + else + finally
> - finally выполнятся в конце в любом случае не зависимо от наличия ошибок











