
Допустим у нас для теста есть вот такая функция для деления, потенциально в качестве делителя мы можем получить нуль, соответственно мы ожидаем это. и в случае возникновения ошибки, мы выводим ошибку с текстом:

```python

def division(a: int | float, b: int | float) -> float | ZeroDivisionError:    
    """    
    Returns the result of dividing a by b    
    
    Raises:    
        ZeroDivisionError: If b is 0    
    """    
    try:    
        return a / b    
    except ZeroDivisionError:    
        raise ZeroDivisionError("Division by zero is not allowed")

```

Теперь мы хотим написать тест, отлавливается ли у нас данное исключение:

```python

    """    
    Test that a ZeroDivisionError is raised when the second argument is 0    
    """    
    with pytest.raises(ZeroDivisionError) as excinfo:    
        division(1, 0)    
    assert str(excinfo.value) == "Division by zero is not allowed"

```

Тест пройдет успешно, если наше исключение возникнет.